nome = input('Digite seu nome completo: ').strip()
print('Analisando seu nome...')
print(f'Seu nome em maiúscula é {nome.upper()}')
print(f'Seu nome em minúscula é {nome.lower()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(' ')} Letras')
divisao = nome.split()
print(f'Seu primeiro nome é {divisao[0]} e ele tem {len(divisao[0])} Letras')
